parameters:
#    blog.example.class: Skl\BlogBundle\Example

services:
#    blog.example:
#        class: %blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        blog.antispam:
               class: Skl\BlogBundle\Antispam\SklAntispam
               arguments: [@mailer, %locale%, 3]
               
       
        
        