<?php

namespace Sdz\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CproduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CproduitsRepository extends EntityRepository
{
}
